/**
 * Storage abstraction (Phase 11A). The application never touches the filesystem
 * (or any vendor SDK) directly — it goes through a StorageDriver. This keeps
 * RIFTARA independent of Supabase Storage and portable to Ubuntu/PostgreSQL.
 *
 * A storage `key` is an opaque, driver-agnostic path generated by the document
 * service (never a user-supplied filename and never a public URL).
 */

export interface PutObjectInput {
  key: string;
  data: Buffer;
  contentType: string;
}

export interface StorageDriver {
  readonly name: string;
  /** Store bytes at `key`, creating any intermediate structure. */
  put(input: PutObjectInput): Promise<void>;
  /** Read the full object. Throws NOT_FOUND when the key is absent. */
  get(key: string): Promise<Buffer>;
  /** Whether an object exists at `key`. */
  exists(key: string): Promise<boolean>;
  /** Remove the object at `key`. Absent keys resolve without error. */
  delete(key: string): Promise<void>;
}
