import 'server-only';
import PDFDocument from 'pdfkit';

/**
 * Branded PDF generation (BRD 115-116) using PDFKit (no headless browser).
 * Produces management-ready executive reports and leasing proposals.
 */

const BROWN = '#3A2B1F';
const GOLD = '#C9A96A';
const GREY = '#6B6B68';
const LIGHT = '#F4EFE8';

export interface PdfKpi {
  label: string;
  value: string;
  sub?: string;
}

export interface PdfSection {
  title: string;
  /** Simple paragraph text. */
  body?: string;
  /** Two-column key/value facts. */
  facts?: Array<{ label: string; value: string }>;
  /** Table with a header row. */
  table?: { headers: string[]; rows: string[][] };
  /** Bulleted list. */
  bullets?: string[];
}

export interface ExecutiveReportInput {
  title: string;
  subtitle: string;
  organizationName: string;
  periodLabel: string;
  scopeLabel: string;
  generatedBy: string;
  kpis: PdfKpi[];
  sections: PdfSection[];
  confidentiality?: string;
}

function collect(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk as Buffer));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}

export async function generateExecutiveReportPdf(input: ExecutiveReportInput): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margin: 48, bufferPages: true });
  const done = collect(doc);
  const pageWidth = doc.page.width - 96;

  // --- Cover band ----------------------------------------------------------
  doc.rect(0, 0, doc.page.width, 160).fill(BROWN);
  doc.fillColor(GOLD).fontSize(26).font('Helvetica-Bold').text('RIFTARA', 48, 46, { characterSpacing: 3 });
  doc.fillColor('#D9CFC4').fontSize(9).font('Helvetica').text('ENTERPRISE PROPERTY PLATFORM', 48, 78, { characterSpacing: 2 });
  doc.fillColor('#FFFFFF').fontSize(19).font('Helvetica-Bold').text(input.title, 48, 104, { width: pageWidth });
  doc.fillColor('#D9CFC4').fontSize(10).font('Helvetica').text(`${input.subtitle} · ${input.periodLabel}`, 48, 132);

  doc.moveDown(2);
  doc.y = 184;
  doc.fillColor(GREY).fontSize(9).font('Helvetica');
  doc.text(`Organization: ${input.organizationName}`, 48, doc.y);
  doc.text(`Scope: ${input.scopeLabel}`);
  doc.text(`Generated by ${input.generatedBy} on ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`);

  // --- KPI grid ------------------------------------------------------------
  doc.moveDown(1);
  let kpiY = doc.y + 8;
  const cols = 3;
  const gap = 12;
  const cardWidth = (pageWidth - gap * (cols - 1)) / cols;
  const cardHeight = 58;

  input.kpis.forEach((kpi, index) => {
    const col = index % cols;
    const row = Math.floor(index / cols);
    const x = 48 + col * (cardWidth + gap);
    const y = kpiY + row * (cardHeight + gap);
    doc.roundedRect(x, y, cardWidth, cardHeight, 6).fill(LIGHT);
    doc.fillColor(GREY).fontSize(8).font('Helvetica').text(kpi.label.toUpperCase(), x + 10, y + 10, { width: cardWidth - 20, characterSpacing: 0.5 });
    doc.fillColor(BROWN).fontSize(15).font('Helvetica-Bold').text(kpi.value, x + 10, y + 24, { width: cardWidth - 20 });
    if (kpi.sub) doc.fillColor(GREY).fontSize(7.5).font('Helvetica').text(kpi.sub, x + 10, y + 43, { width: cardWidth - 20 });
  });

  doc.y = kpiY + Math.ceil(input.kpis.length / cols) * (cardHeight + gap) + 8;

  // --- Sections ------------------------------------------------------------
  for (const section of input.sections) {
    ensureSpace(doc, 80);
    doc.moveDown(0.5);
    doc.fillColor(BROWN).fontSize(13).font('Helvetica-Bold').text(section.title, 48, doc.y);
    doc.moveTo(48, doc.y + 2).lineTo(48 + 40, doc.y + 2).lineWidth(2).strokeColor(GOLD).stroke();
    doc.moveDown(0.6);

    if (section.body) {
      doc.fillColor('#1F1A16').fontSize(9.5).font('Helvetica').text(section.body, { width: pageWidth, lineGap: 2 });
      doc.moveDown(0.4);
    }

    if (section.facts) {
      const factCols = 2;
      const factWidth = pageWidth / factCols;
      section.facts.forEach((fact, index) => {
        const col = index % factCols;
        if (col === 0 && index > 0) doc.moveDown(0.1);
        const x = 48 + col * factWidth;
        const y = doc.y;
        doc.fillColor(GREY).fontSize(8.5).font('Helvetica').text(fact.label, x, y, { width: factWidth - 8, continued: false });
        doc.fillColor(BROWN).fontSize(9.5).font('Helvetica-Bold').text(fact.value, x, y + 11, { width: factWidth - 8 });
        if (col === factCols - 1) doc.moveDown(1.4);
      });
      doc.moveDown(0.4);
    }

    if (section.bullets) {
      for (const bullet of section.bullets) {
        ensureSpace(doc, 20);
        const y = doc.y;
        doc.circle(52, y + 5, 1.5).fill(GOLD);
        doc.fillColor('#1F1A16').fontSize(9.5).font('Helvetica').text(bullet, 60, y, { width: pageWidth - 12, lineGap: 1 });
        doc.moveDown(0.3);
      }
      doc.moveDown(0.3);
    }

    if (section.table) {
      renderTable(doc, section.table, pageWidth);
      doc.moveDown(0.6);
    }
  }

  // --- Footer on every page -----------------------------------------------
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i += 1) {
    doc.switchToPage(i);
    const footerY = doc.page.height - 34;
    doc.moveTo(48, footerY).lineTo(doc.page.width - 48, footerY).lineWidth(0.5).strokeColor('#E6E0D8').stroke();
    doc.fillColor(GREY).fontSize(7.5).font('Helvetica');
    doc.text(input.confidentiality ?? 'Confidential — RIFTARA Enterprise Property Platform', 48, footerY + 6, { width: pageWidth / 2 });
    doc.text(`Page ${i - range.start + 1} of ${range.count}`, 48, footerY + 6, { width: pageWidth, align: 'right' });
  }

  doc.end();
  return done;
}

function ensureSpace(doc: PDFKit.PDFDocument, needed: number): void {
  if (doc.y + needed > doc.page.height - 60) doc.addPage();
}

function renderTable(doc: PDFKit.PDFDocument, table: { headers: string[]; rows: string[][] }, width: number): void {
  const colCount = table.headers.length;
  const colWidth = width / colCount;
  const startX = 48;
  let y = doc.y;

  // Header
  doc.rect(startX, y, width, 20).fill(BROWN);
  table.headers.forEach((header, index) => {
    doc.fillColor('#FFFFFF').fontSize(8).font('Helvetica-Bold').text(header, startX + index * colWidth + 6, y + 6, {
      width: colWidth - 12,
      align: index === 0 ? 'left' : 'right',
    });
  });
  y += 20;

  // Rows
  table.rows.forEach((row, rowIndex) => {
    if (y + 18 > doc.page.height - 60) {
      doc.addPage();
      y = doc.y;
    }
    if (rowIndex % 2 === 1) doc.rect(startX, y, width, 18).fill(LIGHT);
    row.forEach((cell, index) => {
      doc.fillColor('#1F1A16').fontSize(8).font('Helvetica').text(cell, startX + index * colWidth + 6, y + 5, {
        width: colWidth - 12,
        align: index === 0 ? 'left' : 'right',
      });
    });
    y += 18;
  });

  doc.y = y + 4;
}
